---
  - name: Create influxdb directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - "{{ influxdb_home }}"
    tags:
      - influxdb

  - name: Unpacking influxdb
    unarchive:
      src: packages/influxdb-1.3.5_linux_amd64.tar.gz
      dest: "{{influxdb_home}}"
      extra_opts: "--strip-components=2"
    tags:
      - influxdb

  - name: Create configuration
    template:
      src: "{{item}}"
      dest: "{{influxdb_home}}"
    with_items:
      - influxdb.conf
      - influxd.sh
    tags:
      - influxdb

  - name: Create Kraken database
    influxdb_database:
      hostname: "{{groups['central'][0]}}"
      database_name: "{{influxdb_database}}"
      state: present
    tags:
      - influxdb
