---
  - name: Create orientdb directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - "{{ orientdb_home }}"
    tags:
      - orientdb


  - name: Unpacking orientdb
    unarchive:
      src: packages/orientdb-community-2.2.29.tar.gz
      dest: "{{orientdb_home}}"
      extra_opts: "--strip-components=1"
    tags:
      - orientdb

  - name: Delete sample databases
    file:
      path: "{{orientdb_home}}/databases/{{item}}"
      state: absent
    with_items:
      - GratefulDeadConcerts
    tags:
      - orientdb

  - name: Configuring
    blockinfile:
      path: "{{orientdb_home}}/config/orientdb-server-config.xml"
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      insertafter: "<users>"
      content: |
          <user resources="*" name="{{orientdb_user}}" password="{{orientdb_password}}"/>
          <user resources="connect,server.listDatabases,server.dblist" password="guest" name="guest"/>
    tags:
      - orientdb

  - name: Create startup script
    vars:
      process_name: orientdb
      process_cmdline: "nohup bin/server.sh >/dev/null 2>&1"
    template:
      src: "statup"
      dest: "{{orientdb_home}}/orientdb-ctl.sh"
      mode: 0755
    tags:
      - orientdb

  - name: Create database
    uri:
      url: "http://{{ansible_hostname}}:2480/database/{{orientdb_database}}/plocal"
      method: POST
      user: "{{orientdb_user}}"
      password: "{{orientdb_password}}"
      status_code: "200,409"
    tags:
      - orientdb
