---
  - name: Create grafana directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - "{{ grafana_home }}"
    tags:
      - grafana

  - name: Unpacking grafana
    unarchive:
      src: packages/grafana-4.5.1.linux-x64.tar.gz
      dest: "{{grafana_home}}"
      extra_opts: "--strip-components=2"
    tags:
      - grafana

  - name: Create startup script
    vars:
      process_cmdline: "nohup usr/bin/grafana-server >/dev/null 2>&1"
      process_name: grafana
    template:
      src: "startup"
      dest: "{{grafana_home}}/grafana-ctl.sh"
      mode: 0755
    notify: restart grafana
    tags:
      - grafana